name: Deploy to GitHub Pages

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker compose -f docker-compose.yml up --build --no-cache -d
      
    - name: Copy build from container
      run: |
        docker cp $(docker compose ps -q app):/app/build ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build